# Generated by Django 5.0 on 2024-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urls',
            field=models.TextField(blank=True),
        ),
    ]
