# Generated by Django 5.0 on 2024-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='setting',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.TextField(blank=True),
        ),
    ]
