# Generated by Django 5.0 on 2024-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_setting_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='html_page1',
            field=models.TextField(blank=True, default='<xmp></xmp>'),
        ),
        migrations.AddField(
            model_name='post',
            name='html_page2',
            field=models.TextField(blank=True, default='<xmp></xmp>'),
        ),
        migrations.AddField(
            model_name='post',
            name='html_page3',
            field=models.TextField(blank=True, default='<xmp></xmp>'),
        ),
        migrations.AddField(
            model_name='post',
            name='modelx',
            field=models.TextField(blank=True),
        ),
    ]
