# Generated by Django 5.0 on 2024-02-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_url_admin_post_url_context_post_url_modelx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url_admin',
            new_name='admin_context',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url_modelx',
            new_name='modelx_context',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url_setting',
            new_name='setting_context',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url_view',
            new_name='view_context',
        ),
    ]
