# Generated by Django 5.0 on 2024-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_url_admin_post_admin_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html1_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='html2_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='html3_context',
            field=models.TextField(blank=True),
        ),
    ]
