# Generated by Django 5.0 on 2024-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_html1_context_post_html2_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html_page1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='html_page2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='html_page3',
            field=models.TextField(blank=True),
        ),
    ]
