# Generated by Django 5.0 on 2024-02-19 06:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_post_comments_cum_id_rename_cmt_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugx',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
